import type { Metadata } from "next";
import localFont from "next/font/local";
import { Header } from './_components/Header/header'
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  auth,
  modal,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        {children}
        {/* ★ ↓: Parallel & Intercepting Routes によるモーダル表示 */}
        {auth}
        {modal}
      </body>
    </html>
  );
}
